# Site settings
description: A blog about lorem ipsum dolor sit amet
baseurl: "/will-jekyll-template" # the subpath of your site, e.g. /blog
url: "http://douglas-mason.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Douglas Mason
user_description: Always learning, always sharing, never without coffee
user_title: Software Engineer
email: anon@anon.com
twitter_username: douglas_mason
github_username:  douglas-mason
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
